"""Add read column to threads

Revision ID: 65a19d858818
Revises:
Create Date: 2025-11-04 19:26:58.598501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a19d858818'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_state')
    op.drop_table('schema_migrations')
    op.drop_column('label_queue', 'status')
    op.drop_column('label_queue', 'queued_at')
    op.drop_index(op.f('idx_product_sizes_barcode'), table_name='product_sizes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_product_sizes_barcode'), 'product_sizes', ['barcode'], unique=1)
    op.add_column('label_queue', sa.Column('queued_at', sa.TEXT(), nullable=True))
    op.add_column('label_queue', sa.Column('status', sa.TEXT(), server_default=sa.text("'queued'"), nullable=True))
    op.create_table('schema_migrations',
    sa.Column('filename', sa.TEXT(), nullable=True),
    sa.Column('applied_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('filename')
    )
    op.create_table('agent_state',
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###
