"""Add orders system models

Revision ID: 9107f16139f0
Revises: 65a19d858818
Create Date: 2026-01-07 17:26:16.576945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9107f16139f0'
down_revision: Union[str, Sequence[str], None] = '65a19d858818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allegro_replied_discussions',
    sa.Column('discussion_id', sa.String(), nullable=False),
    sa.Column('replied_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('discussion_id')
    )
    op.create_table('allegro_replied_threads',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('replied_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('label_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('label_data', sa.Text(), nullable=True),
    sa.Column('ext', sa.String(), nullable=True),
    sa.Column('last_order_data', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('external_order_id', sa.String(), nullable=True),
    sa.Column('shop_order_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('user_login', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('order_source_id', sa.Integer(), nullable=True),
    sa.Column('order_status_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('date_add', sa.Integer(), nullable=True),
    sa.Column('date_confirmed', sa.Integer(), nullable=True),
    sa.Column('date_in_status', sa.Integer(), nullable=True),
    sa.Column('delivery_method', sa.String(), nullable=True),
    sa.Column('delivery_method_id', sa.Integer(), nullable=True),
    sa.Column('delivery_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_fullname', sa.String(), nullable=True),
    sa.Column('delivery_company', sa.String(), nullable=True),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('delivery_city', sa.String(), nullable=True),
    sa.Column('delivery_postcode', sa.String(), nullable=True),
    sa.Column('delivery_country', sa.String(), nullable=True),
    sa.Column('delivery_country_code', sa.String(length=2), nullable=True),
    sa.Column('delivery_point_id', sa.String(), nullable=True),
    sa.Column('delivery_point_name', sa.String(), nullable=True),
    sa.Column('delivery_point_address', sa.String(), nullable=True),
    sa.Column('delivery_point_postcode', sa.String(), nullable=True),
    sa.Column('delivery_point_city', sa.String(), nullable=True),
    sa.Column('invoice_fullname', sa.String(), nullable=True),
    sa.Column('invoice_company', sa.String(), nullable=True),
    sa.Column('invoice_nip', sa.String(), nullable=True),
    sa.Column('invoice_address', sa.String(), nullable=True),
    sa.Column('invoice_city', sa.String(), nullable=True),
    sa.Column('invoice_postcode', sa.String(), nullable=True),
    sa.Column('invoice_country', sa.String(), nullable=True),
    sa.Column('want_invoice', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_method_cod', sa.Boolean(), nullable=True),
    sa.Column('payment_done', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_comments', sa.Text(), nullable=True),
    sa.Column('admin_comments', sa.Text(), nullable=True),
    sa.Column('courier_code', sa.String(), nullable=True),
    sa.Column('delivery_package_module', sa.String(), nullable=True),
    sa.Column('delivery_package_nr', sa.String(), nullable=True),
    sa.Column('products_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('idx_orders_date_add', 'orders', ['date_add'], unique=False)
    op.create_index('idx_orders_platform', 'orders', ['platform'], unique=False)
    op.create_table('printed_orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('printed_at', sa.String(), nullable=True),
    sa.Column('last_order_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_order_value', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('courier_code', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_status_logs_order_id', 'order_status_logs', ['order_id'], unique=False)
    op.create_index('idx_order_status_logs_timestamp', 'order_status_logs', ['timestamp'], unique=False)
    op.create_table('product_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index('idx_product_sizes_product_id_size', 'product_sizes', ['product_id', 'size'], unique=False)
    op.create_table('purchase_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.String(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sales_sale_date', 'sales', ['sale_date'], unique=False)
    op.create_table('allegro_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_size_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.String(), nullable=True),
    sa.Column('publication_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_sizes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id')
    )
    op.create_table('allegro_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=True),
    sa.Column('product_size_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('competitor_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('competitor_seller', sa.String(), nullable=True),
    sa.Column('competitor_url', sa.String(), nullable=True),
    sa.Column('competitor_delivery_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_sizes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_allegro_price_history_offer_recorded_at', 'allegro_price_history', ['offer_id', 'recorded_at'], unique=False)
    op.create_index('idx_allegro_price_history_product_size', 'allegro_price_history', ['product_size_id'], unique=False)
    op.create_index('idx_allegro_price_history_recorded_at', 'allegro_price_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_allegro_price_history_offer_id'), 'allegro_price_history', ['offer_id'], unique=False)
    op.create_table('order_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_product_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('ean', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_brutto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('auction_id', sa.String(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('product_size_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_sizes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_products_ean', 'order_products', ['ean'], unique=False)
    op.create_index('idx_order_products_order_id', 'order_products', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_products_order_id', table_name='order_products')
    op.drop_index('idx_order_products_ean', table_name='order_products')
    op.drop_table('order_products')
    op.drop_index(op.f('ix_allegro_price_history_offer_id'), table_name='allegro_price_history')
    op.drop_index('idx_allegro_price_history_recorded_at', table_name='allegro_price_history')
    op.drop_index('idx_allegro_price_history_product_size', table_name='allegro_price_history')
    op.drop_index('idx_allegro_price_history_offer_recorded_at', table_name='allegro_price_history')
    op.drop_table('allegro_price_history')
    op.drop_table('allegro_offers')
    op.drop_index('idx_sales_sale_date', table_name='sales')
    op.drop_table('sales')
    op.drop_table('purchase_batches')
    op.drop_index('idx_product_sizes_product_id_size', table_name='product_sizes')
    op.drop_table('product_sizes')
    op.drop_index('idx_order_status_logs_timestamp', table_name='order_status_logs')
    op.drop_index('idx_order_status_logs_order_id', table_name='order_status_logs')
    op.drop_table('order_status_logs')
    op.drop_table('users')
    op.drop_table('shipping_thresholds')
    op.drop_table('products')
    op.drop_table('printed_orders')
    op.drop_index('idx_orders_platform', table_name='orders')
    op.drop_index('idx_orders_date_add', table_name='orders')
    op.drop_table('orders')
    op.drop_table('label_queue')
    op.drop_table('app_settings')
    op.drop_table('allegro_replied_threads')
    op.drop_table('allegro_replied_discussions')
    # ### end Alembic commands ###
