"""Create order_events table for raw Allegro event tracking.

Revision ID: g8b9c0d1e2f3
Revises: f7a8b9c0d1e2
Create Date: 2025-04-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g8b9c0d1e2f3'
down_revision = 'f7a8b9c0d1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('allegro_event_id', sa.String(length=64), nullable=False),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('occurred_at', sa.DateTime(), nullable=False),
        sa.Column('payload_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('allegro_event_id')
    )
    op.create_index('idx_order_events_allegro_event_id', 'order_events', ['allegro_event_id'], unique=False)
    op.create_index('idx_order_events_event_type', 'order_events', ['event_type'], unique=False)
    op.create_index('idx_order_events_occurred_at', 'order_events', ['occurred_at'], unique=False)
    op.create_index('idx_order_events_order_id', 'order_events', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_events_order_id', table_name='order_events')
    op.drop_index('idx_order_events_occurred_at', table_name='order_events')
    op.drop_index('idx_order_events_event_type', table_name='order_events')
    op.drop_index('idx_order_events_allegro_event_id', table_name='order_events')
    op.drop_table('order_events')
    # ### end Alembic commands ###
