"""Add shipment_errors table for tracking label generation and shipment errors.

Revision ID: h9c0d1e2f3g4
Revises: g8b9c0d1e2f3
Create Date: 2025-04-01 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'h9c0d1e2f3g4'
down_revision = 'g8b9c0d1e2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'shipment_errors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('error_type', sa.String(length=64), nullable=False),
        sa.Column('error_code', sa.String(length=32), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('delivery_method', sa.String(length=255), nullable=True),
        sa.Column('raw_response', sa.Text(), nullable=True),
        sa.Column('resolved', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shipment_errors_created_at', 'shipment_errors', ['created_at'], unique=False)
    op.create_index('idx_shipment_errors_delivery_method', 'shipment_errors', ['delivery_method'], unique=False)
    op.create_index('idx_shipment_errors_error_type', 'shipment_errors', ['error_type'], unique=False)
    op.create_index('idx_shipment_errors_order_id', 'shipment_errors', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shipment_errors_order_id', table_name='shipment_errors')
    op.drop_index('idx_shipment_errors_error_type', table_name='shipment_errors')
    op.drop_index('idx_shipment_errors_delivery_method', table_name='shipment_errors')
    op.drop_index('idx_shipment_errors_created_at', table_name='shipment_errors')
    op.drop_table('shipment_errors')
    # ### end Alembic commands ###
