version: '3'

services:
  magazyn_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.magazyn.rule=Host(`magazyn.retrievershop.pl`)"
      - "traefik.http.routers.magazyn.entrypoints=https"
      - "traefik.http.routers.magazyn.tls=true"
      - "traefik.http.services.magazyn.loadbalancer.server.port=80"
      - "traefik.http.services.magazyn.loadbalancer.server.scheme=http" 
networks:
  proxy:
    external: true