ENV_INFO = {
    "API_TOKEN": ("API Token", "BaseLinker API token used to fetch new orders"),
    "PAGE_ACCESS_TOKEN": ("Page Access Token", "Messenger page token for sending notifications"),
    "RECIPIENT_ID": ("Recipient ID", "Messenger recipient ID that receives alerts"),
    "STATUS_ID": ("Status ID", "Order status ID to filter orders for printing"),
    "PRINTER_NAME": ("Printer Name", "Name of the CUPS printer to use"),
    "CUPS_SERVER": ("CUPS Server", "Hostname of a remote CUPS server"),
    "CUPS_PORT": ("CUPS Port", "Port of the remote CUPS server"),
    "POLL_INTERVAL": ("Poll Interval", "Seconds between polling for orders"),
    "QUIET_HOURS_START": ("Quiet Hours Start", "Start hour for muting printing (24h format)"),
    "QUIET_HOURS_END": ("Quiet Hours End", "End hour for muting printing (24h format)"),
    "TIMEZONE": ("Timezone", "IANA timezone used for quiet hour checks"),
    "PRINTED_EXPIRY_DAYS": ("Printed Expiry Days", "Days to keep printed order IDs in the database"),
    "LOG_LEVEL": ("Log Level", "Logging level for the printing agent"),
    "LOG_FILE": ("Log File", "Path to the agent log file"),
    "DB_PATH": ("Database Path", "Path to the SQLite database file"),
    "SECRET_KEY": ("Secret Key", "Secret key for Flask sessions"),
    "FLASK_DEBUG": ("Flask Debug", "Set to 1 to enable Flask debug mode"),
    "FLASK_ENV": ("Flask Environment", "Flask configuration environment"),
    "ENABLE_HTTP_SERVER": ("Enable HTTP Server", "Set to 1 to start the HTTP server"),
    "HTTP_PORT": ("HTTP Port", "Port used by the HTTP server"),
}
